### ISSUE TITLE
3列数据会报错：The method '>' was called on null.

### ISSUE THREAD

**Issue by klniu** [yangyxd/flutter_picker#126]
使用代码库中的example，在showIcons中多加入一维数据，向下拖动时就会出现错误，而且第三维数据刷新不出来：

```dart
  showPickerIcons(BuildContext context) {
    Picker(
      adapter: PickerDataAdapter(data: [
        PickerItem(text: Icon(Icons.add), value: Icons.add, children: [
          PickerItem(text: Icon(Icons.more)),
          PickerItem(text: Icon(Icons.aspect_ratio)),
          PickerItem(text: Icon(Icons.android)),
          PickerItem(text: Icon(Icons.menu), children: [
            // 测试：多加了一维数据
            PickerItem(text: Icon(Icons.account_box)),
            PickerItem(text: Icon(Icons.analytics)),
          ]),
        ]),
        PickerItem(text: Icon(Icons.title), value: Icons.title, children: [
          PickerItem(text: Icon(Icons.more_vert)),
          PickerItem(text: Icon(Icons.ac_unit)),
          PickerItem(text: Icon(Icons.access_alarm)),
          PickerItem(text: Icon(Icons.account_balance)),
        ]),
        PickerItem(text: Icon(Icons.face), value: Icons.face, children: [
          PickerItem(text: Icon(Icons.add_circle_outline)),
          PickerItem(text: Icon(Icons.add_a_photo)),
          PickerItem(text: Icon(Icons.access_time)),
          PickerItem(text: Icon(Icons.adjust)),
        ]),
        PickerItem(
            text: Icon(Icons.linear_scale),
            value: Icons.linear_scale,
            children: [
              PickerItem(text: Icon(Icons.assistant_photo)),
              PickerItem(text: Icon(Icons.account_balance)),
              PickerItem(text: Icon(Icons.airline_seat_legroom_extra)),
              PickerItem(text: Icon(Icons.airport_shuttle)),
              PickerItem(text: Icon(Icons.settings_bluetooth)),
            ]),
        PickerItem(text: Icon(Icons.close), value: Icons.close),
      ]),
      title: Text("Select Icon"),
      selectedTextStyle: TextStyle(color: Colors.blue),
      onConfirm: (Picker picker, List value) {
        print(value.toString());
        print(picker.getSelectedValues());
      },
    ).show(_scaffoldKey.currentState);
  }

```

错误信息：

```
E/flutter (17268): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method '>' was called on null.
E/flutter (17268): Receiver: null
E/flutter (17268): Tried calling: >(-28.0)
E/flutter (17268): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (17268): #1      double.< (dart:core-patch/double.dart:88:18)
E/flutter (17268): #2      double.<= (dart:core-patch/double.dart:109:37)
E/flutter (17268): #3      FixedExtentScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/list_wheel_scroll_view.dart:495:44)
E/flutter (17268): #4      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:148:43)
E/flutter (17268): #5      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:207:5)
E/flutter (17268): #6      FixedExtentScrollController.jumpToItem (package:flutter/src/widgets/list_wheel_scroll_view.dart:285:16)
E/flutter (17268): #7      PickerWidgetState._buildViews.<anonymous closure>.<anonymous closure> (package:flutter_picker/Picker.dart:528:42)
E/flutter (17268): #8      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (17268): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (17268): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (17268): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (17268): #12     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (17268): #13     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (17268): #14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (17268): #15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (17268): #16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (17268): #17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (17268): #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (17268): 
```

**Comment by yangyxd** [comment]
已修复此问题，谢谢。
