### ISSUE TITLE
Not providing onConfirm results in "Null check operator used on a null value"

### ISSUE THREAD

**Issue by magnuswikhog** [yangyxd/flutter_picker#169]
If I don't provide an event handler for `onConfirm`, I get the following error when closing the dialog:

```
E/flutter (22047): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (22047): #0      Picker.showDialog.<anonymous closure>.<anonymous closure> (package:flutter_picker/Picker.dart:243:30)
E/flutter (22047): #1      Picker.showDialog.<anonymous closure>.<anonymous closure> (package:flutter_picker/Picker.dart:237:30)
```

The problem seems to be on line 243 in `Picker.dart`:

```
                    Navigator.pop<List<int>>(context, selecteds);
                    onConfirm!(this, selecteds); // <-- Results in null check operator error if onConfirm is null
```

**Comment by yangyxd** [comment]
@magnuswikhog  This bug will be fixed in v2.0.4, thanks.
